# Generated by Django 4.2.10 on 2024-02-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myclients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('adress1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
