# Generated by Django 4.2.10 on 2024-02-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myclients',
            options={'verbose_name': 'Myclients', 'verbose_name_plural': 'Myclients'},
        ),
    ]
